remote_theme: trylaarsdam/jekyll-theme-console
markdown: kramdown

theme: trylaarsdam/jekyll-theme-console
style: light
header_pages:
  - index.md
  - team.md
  - contact.md
footer: '© 2021 Windy City Lab, LLC -- all rights reserved -- follow us on <a href="https://twitter.com/windycitylab">twitter</a>'
